In [1]:
import Pkg
Pkg.add("CSV")
Pkg.add("Plots")
Pkg.add("DataFrames")
Pkg.add("Statistics")

   Updating registry at `~/.julia/registries/General`
######################################################################### 100.0%
  Resolving package versions...
  Installed ZeroMQ_jll ────── v4.3.2+5
  Installed FFTW_jll ──────── v3.3.9+6
  Installed OpenSpecFun_jll ─ v0.5.3+4
  Installed Zlib_jll ──────── v1.2.11+18
######################################################################### 100.0%
No Changes to `~/.julia/environments/v1.5/Project.toml`
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [f5851436] ↑ FFTW_jll v3.3.9+5 ⇒ v3.3.9+6
  [efe28fd5] ↑ OpenSpecFun_jll v0.5.3+3 ⇒ v0.5.3+4
  [8f1865be] ↑ ZeroMQ_jll v4.3.2+4 ⇒ v4.3.2+5
  [83775a58] ↑ Zlib_jll v1.2.11+17 ⇒ v1.2.11+18
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`

In [2]:
using Random
using CSV
using Plots
using DataFrames
using Statistics
using LinearAlgebra

┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1278

In [115]:
df = CSV.read("national.csv")

217340×311 DataFrame. Omitted printing of 309 columns
│ Row    │ sitecode │ sitename                                           │
│        │ String   │ String                                             │
├────────┼──────────┼────────────────────────────────────────────────────┤
│ 1      │ XX       │ United States (XX)                                 │
│ 2      │ XX       │ United States (XX)                                 │
│ 3      │ XX       │ United States (XX)                                 │
│ 4      │ XX       │ United States (XX)                                 │
│ 5      │ XX       │ United States (XX)                                 │
│ 6      │ XX       │ United States (XX)                                 │
│ 7      │ XX       │ United States (XX)                                 │
│ 8      │ XX       │ United States (XX)                                 │
│ 9      │ XX       │ United States (XX)                                 │
│ 10     │ XX       │ United States (XX)                                 │
⋮
│ 217330 │ XX       │ United States (XX)                                 │
│ 217331 │ XX       │ United States (XX)                                 │
│ 217332 │ XX       │ United States (XX)                                 │
│ 217333 │ XX       │ United States (XX)                                 │
│ 217334 │ XX       │ United States (XX)                                 │
│ 217335 │ XX       │ United States (XX)                                 │
│ 217336 │ XX       │ United States (XX)                                 │
│ 217337 │ XX       │ United States (XX)                                 │
│ 217338 │ XX       │ United States (XX)                                 │
│ 217339 │ XX       │ United States (XX)                                 │
│ 217340 │ XX       │ United States (XX)                                 │

In [116]:
feature_names = names(df)
for i in 1:size(df, 2)
    println(string(i), "\t", string(feature_names[i]), "\t\t\t", string(eltype(df[!, i])))
end

1	sitecode			String
2	sitename			String
3	sitetype			String
4	sitetypenum			Int64
5	year			Int64
6	survyear			Int64
7	weight			Float64
8	stratum			Int64
9	PSU			Int64
10	record			Float64
11	age			String
12	sex			String
13	grade			String
14	race4			String
15	race7			String
16	stheight			String
17	stweight			String
18	bmi			String
19	bmipct			String
20	qnobese			String
21	qnowt			String
22	q66			String
23	q65			String
24	sexid			String
25	sexid2			String
26	sexpart			String
27	sexpart2			String
28	q8			String
29	q9			String
30	q10			String
31	q11			String
32	q12			String
33	q13			String
34	q14			String
35	q15			String
36	q16			String
37	q17			String
38	q18			String
39	q19			String
40	q20			String
41	q21			String
42	q22			String
43	q23			String
44	q24			String
45	q25			String
46	q26			String
47	q27			String
48	q28			String
49	q29			String
50	q30			String
51	q31			String
52	q32			String
53	q33			String
54	q34			String
55	q35			String
56	q36			String
57	q37			String
58	q38			String
59	q39			String
60	q40			String
61	q41			String
62	q42			String
63	q43			String
64	q44			String
65	q45			String
66	q46			String
67	q47			String
68	q48			String
69	q49			String
70	q50			String
71	q51			String
72	q52			String
73	q53			String
74	q54			String
75	q55			String
76	q56			String
77	q57			String
78	q58			String
79	q59			String
80	q60			String
81	q61			String
82	q62			String
83	q63			String
84	q64			String
85	q67			String
86	q68			String
87	q69			String
88	q70			String
89	q71			String
90	q72			String
91	q73			String
92	q74			String
93	q75			String
94	q76			String
95	q77			String
96	q78			String
97	q79			String
98	q80			String
99	q81			String
100	q82			String
101	q83			String
102	q84			String
103	q85			String
104	q86			String
105	q87			String
106	q88			String
107	q89			String
108	qn8			String
109	qn9			String
110	qn10			String
111	qn11			String
112	qn12			String
113	qn13			String
114	qn14			String
115	qn15			String
116	qn16			String
117	qn17			String
118	qn18			String
119	qn19			String
120	qn20			String
121	qn21			String
122	qn22			String
123	qn23			String
124	qn24			String
125	qn25			String
126	qn26			String
127	qn27			String
128	qn28			String
129	qn29			String
130	qn30			String
131	qn31			String
132	qn32			String
133	qn33			String
134	qn34			String
135	qn35			String
136	qn36			String
137	qn37			String
138	qn38			String
139	qn39			String
140	qn40			String
141	qn41			String
142	qn42			String
143	qn43			String
144	qn44			String
145	qn45			String
146	qn46			String
147	qn47			String
148	qn48			String
149	qn49			String
150	qn50			String
151	qn51			String
152	qn52			String
153	qn53			String
154	qn54			String
155	qn55			String
156	qn56			String
157	qn57			String
158	qn58			String
159	qn59			String
160	qn60			String
161	qn61			String
162	qn62			String
163	qn63			String
164	qn64			String
165	qn67			String
166	qn68			String
167	qn69			String
168	qn70			String
169	qn71			String
170	qn72			String
171	qn73			String
172	qn74			String
173	qn75			String
174	qn76			String
175	qn77			String
176	qn78			String
177	qn79			String
178	qn80			String
179	qn81			String
180	qn82			String
181	qn83			String
182	qn84			String
183	qn85			String
184	qn86			String
185	qn87			String
186	qn88			String
187	qn89			String
188	qnfrcig			String
189	qndaycig			String
190	qnfrevp			String
191	qndayevp			String
192	qnfrcgr			String
193	qndaycgr			String
194	qntb2			String
195	qntb3			String
196	qntb4			String
197	qntb5			String
198	qniudimp			String
199	qnothhpl			String
200	qndualbc			String
201	qnbcnone			String
202	qnfr0			String
203	qnfr1			String
204	qnfr2			String
205	qnveg0			String
206	qnveg1			String
207	qnveg2			String
208	qnveg3			String
209	qnsoda1			String
210	qnsoda2			String
211	qnmilk1			String
212	qnmilk3			String
213	qnbk7day			String
214	qnpa0day			String
215	qnpa7day			String
216	qndlype			String
217	qnnodnt			String
218	qbikehelmet			String
219	qdrivemarijuana			String
220	qcelldriving			String
221	qpropertydamage			String
222	qbullyweight			String
223	qbullygender			String
224	qbullygay			String
225	qchokeself			String
226	qcigschool			String
227	qchewtobschool			String
228	qalcoholschool			String
229	qtypealcohol2			String
230	qhowmarijuana			String
231	qmarijuanaschool			String
232	qcurrentopioid			String
233	qcurrentcocaine			String
234	qcurrentheroin			String
235	qcurrentmeth			String
236	qhallucdrug			String
237	qprescription30d			String
238	qgenderexp			String
239	qtaughtHIV			String
240	qtaughtsexed			String
241	qtaughtstd			String
242	qtaughtcondom			String
243	qtaughtbc			String
244	qdietpop			String
245	qcoffeetea			String
246	qsportsdrink			String
247	qenergydrink			String
248	qsugardrink			String
249	qwater			String
250	qfastfood			String
251	qfoodallergy			String
252	qwenthungry			String
253	qmusclestrength			String
254	qsunscreenuse			String
255	qindoortanning			String
256	qsunburn			String
257	qconcentrating			String
258	qcurrentasthma			String
259	qwheresleep			String
260	qspeakenglish			String
261	qtransgender			String
262	qnbikehelmet			String
263	qndrivemarijuana			String
264	qncelldriving			String
265	qnpropertydamage			String
266	qnbullyweight			String
267	qnbullygender			String
268	qnbullygay			String
269	qnchokeself			String
270	qncigschool			String
271	qnchewtobschool			String
272	qnalcoholschool			String
273	qntypealcohol2			String
274	qnhowmarijuana			String
275	qnmarijuanaschool			String
276	qncurrentopioid			String
277	qncurrentcocaine			String
278	qncurrentheroin			String
279	qncurrentmeth			String
280	qnhallucdrug			String
281	qnprescription30d			String
282	qnillict			String
283	qngenderexp			String
284	qntaughtHIV			String
285	qntaughtsexed			String
286	qntaughtstd			String
287	qntaughtcondom			String
288	qntaughtbc			String
289	qndietpop			String
290	qncoffeetea			String
291	qnsportsdrink			String
292	qnspdrk1			String
293	qnspdrk2			String
294	qnenergydrink			String
295	qnsugardrink			String
296	qnwater			String
297	qnwater1			String
298	qnwater2			String
299	qnwater3			String
300	qnfastfood			String
301	qnfoodallergy			String
302	qnwenthungry			String
303	qnmusclestrength			String
304	qnsunscreenuse			String
305	qnindoortanning			String
306	qnsunburn			String
307	qnconcentrating			String
308	qncurrentasthma			String
309	qnwheresleep			String
310	qnspeakenglish			String
311	qntransgender			String

In [117]:
df = select!(df, Not(:sitename))
df = select!(df, Not(:sitetype))
df = select!(df, Not(:sitetypenum))
df = select!(df, Not(:survyear))
df = select!(df, Not(:weight))
df = select!(df, Not(:stratum))
df = select!(df, Not(:PSU))
df = select!(df, Not(:record))

217340×303 DataFrame. Omitted printing of 296 columns
│ Row    │ sitecode │ year  │ age    │ sex    │ grade  │ race4  │ race7  │
│        │ String   │ Int64 │ String │ String │ String │ String │ String │
├────────┼──────────┼───────┼────────┼────────┼────────┼────────┼────────┤
│ 1      │ XX       │ 1991  │ NA     │ NA     │ 1      │ 3      │ 4      │
│ 2      │ XX       │ 1991  │ NA     │ NA     │ NA     │ NA     │ NA     │
│ 3      │ XX       │ 1991  │ 4      │ NA     │ 2      │ 1      │ 6      │
│ 4      │ XX       │ 1991  │ 5      │ NA     │ 2      │ 1      │ 6      │
│ 5      │ XX       │ 1991  │ 6      │ NA     │ NA     │ 4      │ NA     │
│ 6      │ XX       │ 1991  │ NA     │ 2      │ 4      │ 3      │ 4      │
│ 7      │ XX       │ 1991  │ NA     │ 2      │ 4      │ 3      │ 4      │
│ 8      │ XX       │ 1991  │ 1      │ 2      │ NA     │ 4      │ NA     │
│ 9      │ XX       │ 1991  │ 1      │ 2      │ 3      │ 1      │ 6      │
│ 10     │ XX       │ 1991  │ 1      │ 2      │ 2      │ 4      │ NA     │
⋮
│ 217330 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 3      │ 4      │
│ 217331 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217332 │ XX       │ 2019  │ 7      │ 1      │ 3      │ 2      │ 3      │
│ 217333 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217334 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217335 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217336 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217337 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217338 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 217339 │ XX       │ 2019  │ 7      │ 1      │ 3      │ NA     │ NA     │
│ 217340 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 2      │ 3      │

In [118]:
keep = df[:age].!="NA"
r_df = df[keep, :]
keep = r_df[:grade].!="NA"
r_df = r_df[keep, :]
keep = r_df[:sex].!="NA"
r_df = r_df[keep, :]
keep = r_df[:q41].!=" "
r_df = r_df[keep, :]

199642×303 DataFrame. Omitted printing of 296 columns
│ Row    │ sitecode │ year  │ age    │ sex    │ grade  │ race4  │ race7  │
│        │ String   │ Int64 │ String │ String │ String │ String │ String │
├────────┼──────────┼───────┼────────┼────────┼────────┼────────┼────────┤
│ 1      │ XX       │ 1991  │ 1      │ 2      │ 2      │ 4      │ NA     │
│ 2      │ XX       │ 1991  │ 1      │ 2      │ 1      │ 4      │ 2      │
│ 3      │ XX       │ 1991  │ 1      │ 2      │ 2      │ 3      │ 4      │
│ 4      │ XX       │ 1991  │ 1      │ 2      │ 1      │ 4      │ NA     │
│ 5      │ XX       │ 1991  │ 2      │ 2      │ 1      │ 2      │ 3      │
│ 6      │ XX       │ 1991  │ 2      │ 2      │ 1      │ 1      │ 6      │
│ 7      │ XX       │ 1991  │ 2      │ 2      │ 1      │ 2      │ 3      │
│ 8      │ XX       │ 1991  │ 3      │ 2      │ 1      │ 3      │ 4      │
│ 9      │ XX       │ 1991  │ 3      │ 2      │ 1      │ 1      │ 6      │
│ 10     │ XX       │ 1991  │ 3      │ 2      │ 1      │ 2      │ 3      │
⋮
│ 199632 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 3      │ 4      │
│ 199633 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199634 │ XX       │ 2019  │ 7      │ 1      │ 3      │ 2      │ 3      │
│ 199635 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199636 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199637 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199638 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199639 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199640 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 1      │ 6      │
│ 199641 │ XX       │ 2019  │ 7      │ 1      │ 3      │ NA     │ NA     │
│ 199642 │ XX       │ 2019  │ 7      │ 1      │ 4      │ 2      │ 3      │

In [126]:
r_df = r_df[shuffle(1:end), :]
train_proportion = 0.6
val_proportion = 0.2
n = size(r_df, 1)
println("Size of dataset: ", string(n))

# Put the first ntrain observations in the DataFrame df into the training set, and the rest into the test set
ntrain = convert(Int, round(train_proportion*n))
nval = convert(Int, round(val_proportion*n))

target = r_df[:, :q41]
data = r_df[:, filter(col -> (col != :q41), names(r_df))]

#Now you will split the data to create training and test sets. 

# the following variable records the features of examples in the training set
train_x = data[1:ntrain,:]
val_x = data[ntrain+1:ntrain+nval,:]
# the following variable records the features of examples in the test set
test_x = data[ntrain+nval+1:n,:]
# the following variable records the labels of examples in the training set
train_y = target[1:ntrain,:]
val_y = target[ntrain+1:ntrain+nval,:]
# the following variable records the labels of examples in the test set
test_y = target[ntrain+nval+1:n,:]

Size of dataset: 199642

39929×1 Array{String,2}:
 "1"
 "4"
 "2"
 "1"
 "1"
 "2"
 "1"
 "5"
 "1"
 "1"
 "1"
 "3"
 "1"
 ⋮
 "1"
 "4"
 "1"
 "1"
 "1"
 "2"
 "1"
 "2"
 "1"
 "1"
 "1"
 "4"

In [127]:
println(size(train_x))
println(size(train_y))
println(size(test_x))
println(size(test_y))
println(size(val_x))
println(size(val_y))

(119785, 303)
(119785, 1)
(39929, 303)
(39929, 1)
(39928, 303)
(39928, 1)

In [142]:
"This function converts strings to floating point values.
Strings that cannot be represented as a number (like NA) are converted to zeros"
function string_to_int(str)
    try
        parse(Int, str)
    catch
       0.0
    end
end

string_to_int

In [164]:
function ages(df)
    for i = 1:size(df,1)
        if df[i, :age] == "1"
            df[i, :age] = "12"
        elseif df[i, :age] == "2"
            df[i, :age] = "13"
        elseif df[i, :age] == "3"
            df[i, :age] = "14"
        elseif df[i, :age] == "4"
            df[i, :age] = "15"
        elseif df[i, :age] == "5"
            df[i, :age] = "16"
        elseif df[i, :age] == "6"
            df[i, :age] = "17"           
        elseif df[i, :age] == "7"
            df[i, :age] = "18"
        end
    end
    df[:age] = string_to_int.(df[:age])
    return df
end

ages (generic function with 1 method)

In [165]:
new_train_x = ages(train_x)

119785×303 DataFrame. Omitted printing of 296 columns
│ Row    │ sitecode │ year  │ age   │ sex    │ grade  │ race4  │ race7  │
│        │ String   │ Int64 │ Int64 │ String │ String │ String │ String │
├────────┼──────────┼───────┼───────┼────────┼────────┼────────┼────────┤
│ 1      │ XX       │ 2003  │ 18    │ 2      │ 4      │ 2      │ 3      │
│ 2      │ XX       │ 1993  │ 17    │ 1      │ 2      │ 2      │ 3      │
│ 3      │ XX       │ 2011  │ 16    │ 2      │ 2      │ 3      │ 4      │
│ 4      │ XX       │ 1999  │ 16    │ 2      │ 2      │ 1      │ 6      │
│ 5      │ XX       │ 2009  │ 17    │ 2      │ 3      │ 1      │ 6      │
│ 6      │ XX       │ 1991  │ 15    │ 1      │ 2      │ 1      │ 6      │
│ 7      │ XX       │ 1995  │ 14    │ 2      │ 1      │ 1      │ 6      │
│ 8      │ XX       │ 2015  │ 16    │ 1      │ 3      │ 1      │ 6      │
│ 9      │ XX       │ 1995  │ 17    │ 2      │ 3      │ 3      │ 4      │
│ 10     │ XX       │ 1997  │ 18    │ 1      │ 4      │ 2      │ 3      │
⋮
│ 119775 │ XX       │ 2005  │ 17    │ 1      │ 3      │ 1      │ 6      │
│ 119776 │ XX       │ 1997  │ 17    │ 2      │ 2      │ 3      │ 4      │
│ 119777 │ XX       │ 1997  │ 16    │ 1      │ 2      │ 4      │ NA     │
│ 119778 │ XX       │ 1997  │ 17    │ 2      │ 4      │ 2      │ 3      │
│ 119779 │ XX       │ 1997  │ 15    │ 1      │ 1      │ 3      │ 4      │
│ 119780 │ XX       │ 1991  │ 16    │ 1      │ 2      │ 1      │ 6      │
│ 119781 │ XX       │ 2011  │ 15    │ 1      │ 2      │ 1      │ 6      │
│ 119782 │ XX       │ 2009  │ 16    │ 2      │ 2      │ 3      │ 4      │
│ 119783 │ XX       │ 2007  │ 14    │ 2      │ 1      │ 1      │ 6      │
│ 119784 │ XX       │ 1991  │ 17    │ 2      │ 1      │ 2      │ 3      │
│ 119785 │ XX       │ 2007  │ 16    │ 2      │ 1      │ 1      │ 6      │

In [157]:
typeof(new_train_x[1, :age])

String